#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'AWS_CREDENTIALS_ID',
      defaultValue: '',
      description: 'AWS credentials id, stored in Jenkins credentials'
    )
    string(
      name: 'EXTRA_ARGS',
      defaultValue: '',
      description: 'CloudFormation extra arguments'
    )
    string(
      name: 'REGION',
      defaultValue: '',
      description: 'AWS CLI region name'
    )
    string(
      name: 'STACK_NAME',
      defaultValue: '',
      description: 'CloudFormation stack name'
    )
  }

  stages {
    stage('Delete Stack') {
      steps {
        withAWS(credentials:"${params.AWS_CREDENTIALS_ID}", region:"${params.REGION}") {
          // Check if stack exits. If stack does not exits, return error.
          sh  "aws cloudformation describe-stacks \
              --stack-name ${params.STACK_NAME} \
              ${params.EXTRA_ARGS}" 
  
          // Delete Stack
          sh "aws cloudformation delete-stack \
             --stack-name ${params.STACK_NAME} \
             ${params.EXTRA_ARGS}"
  
          // Wait until Stack is deleted completely
          sh "aws cloudformation wait stack-delete-complete \
             --stack-name ${params.STACK_NAME} \
             ${params.EXTRA_ARGS}"
        }
      }
    }
  }
}
