#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'EXTRA_ARGS',
      defaultValue: '',
      description: 'CloudFormation extra arguments'
    )
    string(
      name: 'INVENTORY_FILE_NAME',
      defaultValue: 'default',
      description: 'Ansible Inventory file name. The file would be stored to $ANSIBLE_INVENTORY_DIR, which is defined in Jenkins Server as an environment variable'
    )
    string(
      name: 'INVENTORY_GROUP_NAME',
      defaultValue: 'centos7',
      description: 'Group name defined in Ansible Inventory file'
    )
    string(
      name: 'REGION',
      defaultValue: '',
      description: 'CloudFormation region'
    )
    string(
      name: 'STACK_NAME',
      defaultValue: '',
      description: 'CloudFormation stack name'
    )
    string(
      name: 'WORKING_DIR',
      defaultValue: 'cfn',
      description: 'Job working directory'
    )
  }

  stages {
    stage('Initialize wokring directory') {
      steps {
        dir ("${params.WORKING_DIR}") {
          cleanWs()
        }
      }
    }

    stage('Create Ansible inventory file') {
      steps {
        dir ("${params.WORKING_DIR}") {
           script {
             def ip4adress = sh(
                               returnStdout: true,
                               script: "aws cloudformation describe-stacks --stack-name ${params.STACK_NAME} --region ${params.REGION} ${params.EXTRA_ARGS} | jq '.Stacks[].Outputs[].OutputValue' | sed -e 's/\"//g' | awk 'NR==2'"
                             ).trim()

             def inventory = """all:
  hosts:
    ${params.INVENTORY_GROUP_NAME}:
      ansible_host: $ip4adress
      ansible_port: 22
      ansible_user: centos
"""

             writeFile file: "${env.ANSIBLE_INVENTORY_DIR}/${params.INVENTORY_FILE_NAME}", text: "$inventory"
          }
        }
      }
    }
  }
}
