#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'AWS_CREDENTIALS_ID',
      defaultValue: '',
      description: 'AWS credentials id, stored in Jenkins credentials'
    )
    string(
      name: 'WORKING_DIR',
      defaultValue: 'cfn',
      description: 'Job working directory'
    )
  }

  stages {
    stage('Upload file') {
      steps {
        withAWS(credentials:"${params.AWS_CREDENTIALS_ID}") {
          dir ("${params.WORKING_DIR}") {
             // Create Stack
             sh "echo 'test text' > test.txt"
  
             // Print CloudFormation create command resutls
             sh "aws s3 cp test.txt s3://tomonorimatsumura/test.txt"
          }
        }
      }
    }
  }
}
